name: Crossy Front Build
on:
  workflow_dispatch:
  push:
    barnches: 
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn lint
      - run: docker build .