name: Crossy Front Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn lintfix
      - run: docker build . --tag crossy-front:lastest
      - uses: docker/login-action@v2
        with:
          registry: harbor.crossyjob.ezyostudio.com
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: docker push harbor.crossyjob.ezyostudio.com/crossy-job/crossy-job-front:latest    
